### ISSUE TITLE
sushi.css加载报错

### ISSUE THREAD

**Issue by wulucxy** [mint-ui/docs#2]
因为不习惯用cooking，我尝试自己通过webpack来实现，现在遇到一个问题是结合sushi页面会报错：
```
Cannot find module "./fonts/icon.eot?h67jts"
```
实际上我在webpack里面是有引入对eot的loader的：
```
{
        test: /\.(eot|woff|ttf|svg)$/,
        loader: 'url-loader?limit=30000&name=[name]-[hash].[ext]'
      }
```
不知道发这里是否合适，麻烦帮忙看看

**Comment by QingWei-Li** [comment]
因为用的 iconfont 生成的字体样式文件，默认引用字体文件会带后面一串`?h67jts `之类的字符。所以你的 loader 配置并没有匹配到那串字符，应该写成
```shell
/\.eot|woff|ttf|svg(\?\S*)?$/
```
