### ISSUE TITLE
为什么组件的回调函数api没有说明呢，

### ISSUE THREAD

**Issue by twolun** [mint-ui/docs#8]
今天用了些组件，发现组件内部有emit回调函数，但文档中没有说明，我想我空可以给你们加上

**Comment by Leopoldthecoder** [comment]
欢迎提 PR。
具体是哪些组件，emit 了什么回调呢？

**Comment by twolun** [comment]
比如果，field组件，我发现里面有
watch: {
    value(val) {
      this.currentValue = val;
    },

    currentValue(val) {
      this.$emit('input', val);
    },

    attr: {
      immediate: true,
      handler(attrs) {
        this.$nextTick(() => {
          const target = [this.$refs.input, this.$refs.textarea];
          target.forEach(el => {
            if (!el || !attrs) return;
            Object.keys(attrs).map(name => el.setAttribute(name, attrs[name]));
          });
        });
      }
    }
  }

**Comment by twolun** [comment]
比如果还有button组件，没有点击的回调，我暂时在button组件外层再加一层div，然后执行click，感觉怪怪的

**Comment by twolun** [comment]
button组件中，已经有执行touchstart事件，顺便emit个回调应该更方便了吧，

**Comment by QingWei-Li** [comment]
$emit('input) 是给 v-model 用的，组件上绑定原生事件是通过 native 修饰符，具体参考 vue 文档，或者 faq.md

**Comment by twolun** [comment]
你说的我明白，但如果我希望在组件input事件时，做些操作，那时不是需要执行一下回调呢

**Comment by QingWei-Li** [comment]
那你 v-on:input
