### ISSUE TITLE
loadmore自动上滑一小段距离

### ISSUE THREAD

**Issue by WYHWYP** [mint-ui/docs#98]
各位大神，谁能指点一下呢？顶部有一个tab切换，但是loadmore加载完数据后，会自动上滑一段距离，显示的内容没有在wrapper里面

**Comment by pokect** [comment]
父容器 添加
.wrapper{
      overflow: scroll;
  }
属性

**Comment by WYHWYP** [comment]
谢谢，您。这个我是加了的，就是数据第一次的时候会上滑动。其他的下拉刷新，上拉加载功能都是好的
